### ISSUE TITLE
Buddy Utages over 101% break imports

### ISSUE THREAD

**Issue by Xinnoh** [j1nxie/kt-maimaidx-site-importer#13]
Terminal Error: Invalid BATCH-MANUAL: scores[12].percent | Expected a number between 0 and 101. | Received 200.3631 [type: number].

utages can't be imported, just discard instead

![Screenshot 2024-06-16 223455](https://github.com/j1nxie/kt-maimaidx-site-importer/assets/30382015/e78f525d-91fa-477f-a5d1-84cbefb6eb2c)

**Comment by j1nxie** [comment]
fixed in #14.
